
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `localdb`
//     Provider:               `Npgsql`
//     Connection String:      `Server=127.0.0.1;Port=5432;Database=dvdrental;User Id=postgres;password=**zapped**;`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `NpgsqlFactory`

// -----------------------------------------------------------------------------------------
// SP function creation is not supported for  `Npgsql`
// -----------------------------------------------------------------------------------------

